### ISSUE TITLE
Add support for Hespori entagle

### ISSUE THREAD

**Issue by deadmeu** [HamzehAdawi/FrozenIcon#1]
It would be nice if there was support for the Hespori entangle i.e. "The Hespori entangles you in some vines!" event.

**Comment by HamzehAdawi** [comment]
Done :)

**Comment by deadmeu** [comment]
Thank you 😄

**Comment by HamzehAdawi** [comment]
It went against Jagex's boss policy, so it did not get approved. Sorry my friend!

    "Indicates the time where a boss mechanic may start or end"

https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

**Comment by deadmeu** [comment]
Aw man... I like to play with the chat box closed and was really looking forward to the visual indicator to replace the chat message...

So even though we have the message provided to the user via the chat box it is still not permitted? I would imagine that rule you linked would only apply to mechanics that aren't telegraphed (e.g. random missiles thrown out by bosses)...

Thanks for trying anyway. I wonder if I can provide feedback/suggestions to Jagex...

**Comment by HamzehAdawi** [comment]
Yeah that's a very fair point honestly. It's not necessarily un-hiding any info that is not already provided in game chat.

Well, this was the PR: 
https://github.com/runelite/plugin-hub/pull/9295

Maybe we can ask them how to request/give feedback to Jagex on this?
